# Let's make IOU

In [1]:
""" Intersection Usion
Args:
    box1 : 2D array [x,y,w,h]
    box2 : single array [x,y,w,h]
    
Returns :
    IoU : range[0,1]
"""

' Intersection Usion\nArgs:\n    box1 : 2D array [x,y,w,h]\n    box2 : single array [x,y,w,h]\n    \nReturns :\n    IoU : range[0,1]\n'

# Define data

In [2]:
import numpy as np

In [3]:
box1 = np.array([[5,5,3,3]])

In [13]:
box1[:,0]

array([5])

In [4]:
box2 = np.array([6,6,3,3])

# calculate iou

In [17]:
intersection_width = np.maximum( np.minimum( box1[:,0]+box1[:,2]*0.5, box2[0]+box2[2]*0.5) - np.maximum( box1[:,0]-box1[:,2]*0.5, box2[0]-box2[2]*0.5),0 )
intersection_height = np.maximum( np.minimum( box1[:,1]+box1[:,3]*0.5, box2[1]+box2[3]*0.5) - np.maximum( box1[:,1]-box1[:,3]*0.5, box2[1]-box2[3]*0.5),0 )                           

In [18]:
intersection_height

array([2.])

In [19]:
intersection_height

array([2.])

In [22]:
inter = intersection_height*intersection_width
inter

array([4.])

In [25]:
union = box1[:,2]*box1[:,3] + box2[2]*box2[3] -inter
union

array([18])

In [ ]:
IOU = 

In [ ]:
lr = np.maximum(
      np.minimum(boxes[:,0]+0.5*boxes[:,2], box[0]+0.5*box[2]) - \
      np.maximum(boxes[:,0]-0.5*boxes[:,2], box[0]-0.5*box[2]),
      0
  )
  tb = np.maximum(
      np.minimum(boxes[:,1]+0.5*boxes[:,3], box[1]+0.5*box[3]) - \
      np.maximum(boxes[:,1]-0.5*boxes[:,3], box[1]-0.5*box[3]),
      0
  )
  inter = lr*tb
  union = boxes[:,2]*boxes[:,3] + box[2]*box[3] - inter
  return inter/union

Reference    
[1]. code, https://github.com/BichenWuUCB/squeezeDet/blob/master/src/utils/util.py 